-- Создание SQL таблиц при помощи чистого SQL

-- ATTORNEY
CREATE TABLE IF NOT EXISTS attorneys (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name       varchar(50)  NOT NULL,
    last_name        varchar(50)  NOT NULL,
    patronymic       varchar(50),
    email            varchar(50)  NOT NULL,
    phone            varchar(20),
    password_hash    varchar(255) NOT NULL,
    is_active        boolean      NOT NULL DEFAULT TRUE,
    created_at       timestamptz  NOT NULL DEFAULT timezone('utc', now()),
    updated_at       timestamptz  NOT NULL DEFAULT timezone('utc', now())
);

-- Модель просила просто index (не unique). Если хочешь уникальность — замени на UNIQUE.
CREATE INDEX IF NOT EXISTS ix_attorneys_email ON attorneys (email);

-- CLIENT
CREATE TABLE IF NOT EXISTS clients (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(255) NOT NULL,
    type              boolean      NOT NULL, -- TRUE: физлицо, FALSE: юрлицо
    email             varchar(50),
    phone             varchar(20)  NOT NULL,
    personal_info     varchar(20),
    address           varchar(255),
    messenger         varchar(50),
    messenger_handle  varchar(50),
    created_at        timestamptz  NOT NULL DEFAULT timezone('utc', now()),
    owner_attorney_id integer,
    CONSTRAINT fk_clients_owner_attorney
        FOREIGN KEY (owner_attorney_id)
        REFERENCES attorneys (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_clients_email             ON clients (email);
CREATE INDEX IF NOT EXISTS ix_clients_owner_attorney_id ON clients (owner_attorney_id);

-- CASE
CREATE TABLE IF NOT EXISTS cases (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    client_id   integer      NOT NULL,
    attorney_id integer,
    status      varchar(50)  NOT NULL,
    description varchar(500),
    created_at  timestamptz  NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT fk_cases_client
        FOREIGN KEY (client_id)
        REFERENCES clients (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_cases_attorney
        FOREIGN KEY (attorney_id)
        REFERENCES attorneys (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_cases_client_id   ON cases (client_id);
CREATE INDEX IF NOT EXISTS ix_cases_attorney_id ON cases (attorney_id);

-- CONTACT
CREATE TABLE IF NOT EXISTS contacts (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(100) NOT NULL,
    personal_info varchar(20),
    phone         varchar(20),
    email         varchar(50),
    created_at    timestamptz  NOT NULL DEFAULT timezone('utc', now()),
    case_id       integer      NOT NULL,
    CONSTRAINT fk_contacts_case
        FOREIGN KEY (case_id)
        REFERENCES cases (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_contacts_case_id ON contacts (case_id);

-- EVENT
CREATE TABLE IF NOT EXISTS events (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255)  NOT NULL,
    description varchar(2000),
    event_type  varchar(50)   NOT NULL,
    event_date  timestamptz   NOT NULL,
    case_id     integer       NOT NULL,
    attorney_id integer       NOT NULL,
    CONSTRAINT fk_events_case
        FOREIGN KEY (case_id)
        REFERENCES cases (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_events_attorney
        FOREIGN KEY (attorney_id)
        REFERENCES attorneys (id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_events_case_id     ON events (case_id);
CREATE INDEX IF NOT EXISTS ix_events_attorney_id ON events (attorney_id);
CREATE INDEX IF NOT EXISTS ix_events_event_date  ON events (event_date);

-- DOCUMENT
CREATE TABLE IF NOT EXISTS documents (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name    varchar(300)  NOT NULL,
    storage_path varchar(1000) NOT NULL,
    checksum     varchar(64), -- SHA-256 hex = 64 символов
    case_id      integer,
    attorney_id  integer,
    created_at   timestamptz   NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT fk_documents_case
        FOREIGN KEY (case_id)
        REFERENCES cases (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_documents_attorney
        FOREIGN KEY (attorney_id)
        REFERENCES attorneys (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_documents_case_id     ON documents (case_id);
CREATE INDEX IF NOT EXISTS ix_documents_attorney_id ON documents (attorney_id);
