"""Переименован Столбец в таблице Documents

Revision ID: 07b4412aa3bb
Revises: fc14f24f4ef6
Create Date: 2025-11-08 20:14:58.425756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b4412aa3bb'
down_revision: Union[str, Sequence[str], None] = 'fc14f24f4ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'contacts', 'personal_info', existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        'contacts', 'phone', existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.add_column(
        'documents', sa.Column('file_size', sa.String(length=64), nullable=True)
    )
    op.drop_column('documents', 'checksum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column(
            'checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.drop_column('documents', 'file_size')
    op.alter_column(
        'contacts', 'phone', existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        'contacts', 'personal_info', existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###
