"""add two tables - Payment, Payment Detail

Revision ID: 6adf039ec74b
Revises: add_mime_type
Create Date: 2025-12-23 09:26:43.028428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adf039ec74b'
down_revision: Union[str, Sequence[str], None] = 'add_mime_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'client_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('attorney_id', sa.Integer(), nullable=False),
        sa.Column('paid', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('paid_str', sa.String(length=512), nullable=False),
        sa.Column('pade_date', sa.Date(), nullable=False),
        sa.Column('paid_deadline', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('taxable', sa.Boolean(), nullable=False),
        sa.Column('condition', sa.String(length=255), nullable=True),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['attorney_id'], ['attorneys.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_client_payments_attorney_id'),
        'client_payments',
        ['attorney_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_client_payments_client_id'),
        'client_payments',
        ['client_id'],
        unique=False,
    )
    op.alter_column(
        'attorneys', 'phone', existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        'outbox',
        'status',
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        'outbox',
        'retry_count',
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'outbox',
        'retry_count',
        existing_type=sa.INTEGER(),
        server_default=sa.text('0'),
        existing_nullable=False,
    )
    op.alter_column(
        'outbox',
        'status',
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        'attorneys', 'phone', existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.drop_index(op.f('ix_client_payments_client_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_attorney_id'), table_name='client_payments')
    op.drop_table('client_payments')
    # ### end Alembic commands ###
