"""Добавление нового поля в таблице documents

Revision ID: 70fe8f8732e5
Revises: 07b4412aa3bb
Create Date: 2025-11-11 11:16:30.610221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fe8f8732e5'
down_revision: Union[str, Sequence[str], None] = '07b4412aa3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents', sa.Column('description', sa.String(length=500), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
