"""Миксины добавлены во все таблицы

Revision ID: 7d484cfff5ff
Revises: a2c0b995a5d5
Create Date: 2025-11-05 14:25:19.637156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d484cfff5ff'
down_revision: Union[str, Sequence[str], None] = 'a2c0b995a5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attorneys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('attorneys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('cases', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('contacts', 'updated_at')
    op.alter_column('clients', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('clients', 'updated_at')
    op.drop_column('cases', 'updated_at')
    op.alter_column('attorneys', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('attorneys', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
