"""add created_at and updated_at to attorneys

Revision ID: a2c0b995a5d5
Revises: 0a8dcda7604a
Create Date: 2025-11-05 11:52:11.809702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c0b995a5d5'
down_revision: Union[str, Sequence[str], None] = '0a8dcda7604a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
