"""Изменено название столбца на правильное

Revision ID: ae12d9ec3e74
Revises: f194b6b764f7
Create Date: 2025-11-13 11:22:37.475703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae12d9ec3e74'
down_revision: Union[str, Sequence[str], None] = 'f194b6b764f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'attorneys', sa.Column('license_id', sa.String(length=50), nullable=False)
    )
    op.drop_constraint(op.f('attorneys_lisence_id_key'), 'attorneys', type_='unique')
    op.create_unique_constraint(None, 'attorneys', ['license_id'])
    op.drop_column('attorneys', 'lisence_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'attorneys',
        sa.Column(
            'lisence_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, 'attorneys', type_='unique')
    op.create_unique_constraint(
        op.f('attorneys_lisence_id_key'),
        'attorneys',
        ['lisence_id'],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column('attorneys', 'license_id')
    # ### end Alembic commands ###
