"""Fix attorney model

Revision ID: afb631cc3dd8
Revises: e0ee2949678b
Create Date: 2025-11-30 14:23:41.834386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb631cc3dd8'
down_revision: Union[str, Sequence[str], None] = 'e0ee2949678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attorneys', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('attorneys', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('attorneys', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('attorneys', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.drop_constraint(op.f('attorneys_license_id_key'), 'attorneys', type_='unique')
    op.drop_constraint(op.f('attorneys_phone_key'), 'attorneys', type_='unique')
    op.create_index(op.f('ix_attorneys_license_id'), 'attorneys', ['license_id'], unique=True)
    op.create_index(op.f('ix_attorneys_phone'), 'attorneys', ['phone'], unique=True)
    op.drop_column('attorneys', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attorneys', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_attorneys_phone'), table_name='attorneys')
    op.drop_index(op.f('ix_attorneys_license_id'), table_name='attorneys')
    op.create_unique_constraint(op.f('attorneys_phone_key'), 'attorneys', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('attorneys_license_id_key'), 'attorneys', ['license_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attorneys', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('attorneys', 'is_verified')
    op.drop_column('attorneys', 'is_superuser')
    op.drop_column('attorneys', 'hashed_password')
    # ### end Alembic commands ###
