"""add telegram_username to attorneys

Revision ID: b875b3fdf17f
Revises: afb631cc3dd8
Create Date: 2025-12-18 16:04:13.723822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b875b3fdf17f'
down_revision: Union[str, Sequence[str], None] = 'afb631cc3dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attorneys', sa.Column('telegram_username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attorneys', 'telegram_username')
    # ### end Alembic commands ###
