"""add table Payment Detail

Revision ID: cce7cc311b4d
Revises: 6adf039ec74b
Create Date: 2025-12-23 09:38:53.734199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce7cc311b4d'
down_revision: Union[str, Sequence[str], None] = '6adf039ec74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attorney_id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('index_address', sa.String(length=6), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('bank_account', sa.String(length=20), nullable=False),
    sa.Column('correspondent_account', sa.String(length=20), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=False),
    sa.Column('bank_recipient', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attorney_id'], ['attorneys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_details_attorney_id'), 'payment_details', ['attorney_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_details_attorney_id'), table_name='payment_details')
    op.drop_table('payment_details')
    # ### end Alembic commands ###
