"""Изменено название столбца

Revision ID: f194b6b764f7
Revises: ced1ebacef76
Create Date: 2025-11-13 11:21:02.187886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f194b6b764f7'
down_revision: Union[str, Sequence[str], None] = 'ced1ebacef76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'attorneys', sa.Column('license_id', sa.String(length=50), nullable=False)
    )
    op.drop_constraint(op.f('attorneys_attorney_id_key'), 'attorneys', type_='unique')
    op.create_unique_constraint(None, 'attorneys', ['license_id'])
    op.drop_column('attorneys', 'attorney_id')
    op.alter_column(
        'cases',
        'description',
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cases',
        'description',
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.add_column(
        'attorneys',
        sa.Column(
            'attorney_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, 'attorneys', type_='unique')
    op.create_unique_constraint(
        op.f('attorneys_attorney_id_key'),
        'attorneys',
        ['attorney_id'],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column('attorneys', 'license_id')
    # ### end Alembic commands ###
