"""New Field for Contacts, Relationship to Attorney

Revision ID: f686a9802746
Revises: cce7cc311b4d
Create Date: 2025-12-24 08:56:14.614211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f686a9802746'
down_revision: Union[str, Sequence[str], None] = 'cce7cc311b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('attorney_id', sa.Integer(), nullable=False))
    op.create_index(
        op.f('ix_contacts_attorney_id'), 'contacts', ['attorney_id'], unique=False
    )
    op.create_foreign_key(
        None, 'contacts', 'attorneys', ['attorney_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_attorney_id'), table_name='contacts')
    op.drop_column('contacts', 'attorney_id')
    # ### end Alembic commands ###
